import { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    slug: 'nagpur-marina-infinity',
    name: 'Nagpur Marina',
    location: 'South Nagpur, Nagpur',
    area: 'South Nagpur',
    pricePerSqft: 5400,
    startingPriceDisplay: '₹67.5 Lakh (All Inclusive)',
    plotSizes: [1250, 1798],
    type: 'residential',
    status: 'available',
    approvals: ['MahaRERA Approved'],
    rera: 'PP1190002502095',
    loanEligible: true,
    description: 'The edge of The Infinity Pool is where ordinary ends. Nagpur Marina by The House of Abhinandan Lodha is inspired by the world’s most iconic marinas. Secure your Alpha Grade Luxury Villa Land today.',
    longDescription: 'Nagpur Marina represents a benchmark in curated luxury villa plotted developments in South Nagpur. Surrounded by rapidly maturing infrastructure including metro connectivity and arterial links, the enclave provides dedicated villa parcels equipped with over 40 lifestyle amenities and resort-grade landscape features.',
    features: [
      '40+ Curated Amenities',
      'Infinity Pool & Deck',
      'Luxury Villa Land Parcels',
      'Alpha Grade Luxury Asset Class',
      'MahaRERA Registered',
      'Paved Internal Access',
    ],
    image: '/PROPERTY/infinitypool.png',
    gallery: [
      '/PROPERTY/infinitypool.png',
      '/hero-bg.png',
      '/7.png',
    ],
    coordinates: { lat: 21.065, lng: 79.055 },
    featured: true,
  },
  {
    slug: 'saraswati-nagari-10',
    name: 'Saraswati Nagari 10',
    location: 'Hingna Road, Nagpur',
    area: 'Hingna',
    pricePerSqft: 2500,
    startingPriceDisplay: 'From ₹25 Lakh',
    plotSizes: [1000, 1200, 2000],
    type: 'residential',
    status: 'available',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    rera: 'P50500081064',
    loanEligible: true,
    description: 'Premium phase of Saraswati Nagari offering large plot configurations with dual approval from NMRDA and RL. Designed for long-term residential value along the flourishing Hingna corridor.',
    longDescription: 'Saraswati Nagari 10 is an advanced residential plotted enclave situated along the Hingna corridor, combining institutional proximity with complete civic infrastructure. Benefiting from NMRDA layout sanction and Release Letter (RL) validation, each plot is fully loan-eligible and ready for immediate registry and construction.',
    additionalDetails: [
      { label: 'MAHADA Colony', value: '300 meters' },
      { label: 'Podar International School', value: '500 meters' },
      { label: 'St. Joseph’s School', value: '1.0 km' },
      { label: 'Narayana Vidyalayam', value: '1.6 km' },
      { label: 'Sanjeevni Hospital', value: '1.7 km' },
    ],
    features: [
      'Clear Title & Legal Documents',
      'NMRDA & RL Sanctioned',
      'Mini Theatre & Clubhouse',
      'Swimming Pool',
      'Banquet Hall & Pavilion',
      'Underground Drainage & Water Lines',
    ],
    image: '/11.png',
    gallery: [
      '/11.png',
      '/hero-bg.png',
      '/8.png',
    ],
    coordinates: { lat: 21.092, lng: 78.989 },
    featured: true,
  },
  {
    slug: 'saraswati-nagari-8',
    name: 'Saraswati Nagari 8',
    location: 'Mouza-Lava, Tah. Nagpur',
    area: 'Amravati Road',
    pricePerSqft: 2000,
    startingPriceDisplay: 'From ₹20 Lakh',
    plotSizes: [1000, 1200, 1500],
    type: 'residential',
    status: 'available',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    rera: 'P50500056182',
    loanEligible: 'Yes — up to 80% Bank Finance',
    description: 'Located at KH. No. 283/2, P.H. No. 4, Mouza-Lava, Tah. Nagpur. Developed by M/s SR Group and promoted by Hey Investor Pvt. Ltd., offering serene living just 80 meters from Amravati Road.',
    longDescription: 'Saraswati Nagari 8 stands as an established residential enclave directly flanking the Amravati Road corridor. The layout delivers high-specification cement roadways, independent water supply, underground sewage networks, and an operational Sewage Treatment Plant (STP), providing uncompromised security and immediate livability.',
    additionalDetails: [
      { label: 'Amravati Road', value: '80 meters' },
      { label: 'Wadi Chouk', value: '2.5 km' },
      { label: 'Sarojini Chauhan High School', value: 'Opposite layout' },
      { label: 'Global Indian Int. School', value: '600 meters' },
    ],
    features: [
      '80m from Amravati Road',
      'Reinforced Cement Concrete Roads',
      'Dedicated Water Supply Line',
      'Sewage Treatment Plant (STP)',
      'Green Gym & Landscaped Parks',
      'Storm Water Drainage System',
    ],
    image: '/PROPERTY/sarasvati8.png',
    gallery: [
      '/PROPERTY/sarasvati8.png',
      '/hero-bg.png',
      '/7.png',
    ],
    coordinates: { lat: 21.155, lng: 78.985 },
    featured: true,
  },
  {
    slug: 'chawre-colony',
    name: 'Chawre Colony',
    location: 'Wanadongri, Nagpur',
    area: 'Hingna & Amravati Corridor',
    pricePerSqft: 1600,
    startingPriceDisplay: 'From ₹16 Lakh',
    plotSizes: [1000, 1200],
    type: 'mixed',
    status: 'available',
    approvals: ['NMRDA Sanctioned'],
    rera: 'P50500031367',
    loanEligible: false,
    description: 'Strategically positioned near Wanadongri in close proximity to Outer Ring Road, Samruddhi Mahamarg link, and Hingna MIDC. Excellent potential for commercial and residential value.',
    longDescription: 'The areas surrounding Amravati Road and Hingna Road are currently experiencing rapid infrastructure acceleration. Chawre Colony offers investors direct access to major connectivity arterial routes, logistics hubs, and educational landmarks like YCCE, with fully developed cement roads and power infrastructure.',
    additionalDetails: [
      { label: 'Outer Ring Road', value: '1.0 km' },
      { label: 'Wanadongari Road', value: '300 meters' },
      { label: 'Ambazari Ordnance Defence Area', value: '1.0 km' },
      { label: 'Shangrilla High School', value: '1.0 km' },
      { label: 'Gajanan Mandir', value: '1.0 km' },
      { label: 'Waddhamna', value: '1.5 km' },
      { label: 'Amravati Road', value: '3.5 km' },
      { label: 'Hingna Road', value: '4.0 km' },
      { label: 'YCCE Campus', value: '4.0 km' },
    ],
    features: [
      'Cement Concrete Roadways',
      'Dedicated Electrical Transformer',
      'Roadside Tree Plantation',
      'Sewage Treatment Plant & Lines',
      'Storm Water Line Network',
      'Integrated Water Source',
    ],
    image: '/PROPERTY/chaware.png',
    gallery: [
      '/PROPERTY/chaware.png',
      '/8.png',
      '/hero-bg.png',
    ],
    coordinates: { lat: 21.098, lng: 78.972 },
    featured: true,
  },
  {
    slug: 'earth-park-2',
    name: 'Earth Park 2',
    location: 'Hingna, Nagpur',
    area: 'Hingna',
    pricePerSqft: 2500,
    startingPriceDisplay: 'From ₹25 Lakh (Res.) / ₹30 Lakh (Comm.)',
    plotSizes: [1000, 1500, 2000],
    type: 'mixed',
    status: 'available',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    loanEligible: 'Yes — up to 80% Bank Finance',
    description: 'Featuring 260 ft Road Touch Commercial Plots (₹3,000 / sq.ft) and 150 ft Road Touch Residential Plots (₹2,500 / sq.ft) with comprehensive site development.',
    longDescription: 'Earth Park 2 commands rare highway geometry with 260 ft road-touch commercial frontage and 150 ft road-touch residential plots in Hingna. Perfectly tailored for investors seeking frontage prominence, high traffic exposure, and NMRA/RL sanction assurance.',
    additionalDetails: [
      { label: 'Hingna Tahsil Office', value: '1.0 km' },
      { label: 'Metro Station', value: '1.2 km' },
      { label: 'Hingna Square', value: '1.5 km' },
    ],
    features: [
      '260 ft Road Touch Commercial Parcels',
      '150 ft Road Touch Residential Parcels',
      'Full On-Site Civil Development',
      'NMRA Sanctioned & RL Plots',
      '80% Bank Finance Available',
    ],
    image: '/9.png',
    gallery: [
      '/9.png',
      '/hero-bg.png',
    ],
    coordinates: { lat: 21.085, lng: 78.965 },
    featured: false,
  },
  {
    slug: 'saraswati-nagari-9',
    name: 'Saraswati Nagari 9 Godhani',
    location: 'Godhani, Nagpur',
    area: 'Godhani',
    pricePerSqft: 2250,
    startingPriceDisplay: 'From ₹22.5 Lakh',
    plotSizes: [1000, 1500, 2000],
    type: 'mixed',
    status: 'available',
    approvals: ['NMRDA Sanctioned'],
    rera: 'P50500056134',
    loanEligible: true,
    description: 'Sanctioned mixed-use plotted layout in Godhani offering clear title residential and commercial opportunities for long-term capital preservation.',
    longDescription: 'Positioned in the expanding North Nagpur growth node of Godhani, Saraswati Nagari 9 combines peaceful community planning with modern municipal services. Each plot provides clear documentation, full utility connections, and NMRDA compliance.',
    features: [
      'Clear Title & Legal Documents',
      'Cement Roads & Street Lighting',
      'Direct Water Line Connection',
      'Underground Sewage Line & STP Plant',
      'Dedicated Garden & Open Spaces',
    ],
    image: '/10.png',
    coordinates: { lat: 21.215, lng: 79.062 },
    featured: false,
  },
  {
    slug: 'earth-park-1',
    name: 'Earth Park 1',
    location: 'Waddhamna, Nagpur',
    area: 'Amravati Road',
    pricePerSqft: 1600,
    startingPriceDisplay: 'From ₹16 Lakh',
    plotSizes: [1000, 1500],
    type: 'residential',
    status: 'available',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    rera: 'P50500054102',
    loanEligible: 'Yes — up to 80% Bank Finance',
    description: 'Upcoming premium residential layout in Waddhamna on the Amravati Road corridor offering wide roads, gated security, and NMRDA/RL approvals.',
    features: [
      'Wide Planned Roads',
      'Street Lighting Infrastructure',
      'Landscaped Green Garden',
      'Reliable Water Supply',
      'Gated Community Enclosure',
    ],
    image: '/6.png',
    coordinates: { lat: 21.142, lng: 78.945 },
    featured: false,
  },
  {
    slug: 'savitri-park',
    name: 'Savitri Park (Phase 1)',
    location: 'Drugdhamna, Lava, Nagpur',
    area: 'Amravati Road',
    pricePerSqft: 1200,
    startingPriceDisplay: 'From ₹12 Lakh',
    plotSizes: [1000, 1500, 2000],
    type: 'residential',
    status: 'coming-soon',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    loanEligible: 'Yes — up to 80% Bank Finance',
    description: 'A planned residential plotted layout designed for modern living in Drugdhamna, Lava. Fully sanctioned with NMRDA & RL approvals.',
    features: [
      'Wide Internal Roads',
      'Street Lights & Power Lines',
      'Landscape Gardens',
      'Water Supply Infrastructure',
      'Gated Layout Boundary',
    ],
    image: '/PROPERTY/savitri.png',
    coordinates: { lat: 21.16, lng: 78.96 },
    featured: false,
  },
  {
    slug: 'kamla-greens',
    name: 'Kamla Greens (Saraswati Nagri 9)',
    location: 'Mouza Godhani, Nagpur (Gramin)',
    area: 'Mouza Godhani',
    pricePerSqft: 2250,
    startingPriceDisplay: 'Sold Out',
    plotSizes: [1000, 1500, 2000],
    type: 'mixed',
    status: 'sold',
    approvals: ['RL Sanctioned'],
    rera: 'P50500056134',
    loanEligible: 'Yes — up to 80% Bank Finance',
    description: 'Successfully developed and 100% sold-out DP road-touched layout at Mouza Godhani, Khasra No. 443/1, 443/2 P.H No. 12.',
    additionalDetails: [
      { label: 'Site Address', value: 'Khasra No. 443/1, 443/2 P.H No. 12 Mouza Godhani, Nagpur' },
      { label: 'Podar International School', value: '500 meters' },
      { label: 'MAHADA Colony', value: '300 meters' },
      { label: 'St. Joseph’s School', value: '1.0 km' },
      { label: 'Godhani Railway Station', value: '1.8 km' },
      { label: 'Max Hospital', value: '5.0 km' },
    ],
    features: [
      'DP Road Touched Frontage',
      'RL Sanctioned Layout',
      '100% Completed Civil Works',
      'Educational Hub Proximity',
      'All Plots Handed Over',
    ],
    image: '/PROPERTY/kamlagreens.png',
    coordinates: { lat: 21.218, lng: 79.068 },
    featured: false,
  },
  {
    slug: 'kuhaasa-residency',
    name: 'Kuhaasa Residency',
    location: 'Wardha Road, Nagpur',
    area: 'Wardha Road',
    pricePerSqft: null,
    startingPriceDisplay: 'Sold Out',
    plotSizes: [1000],
    type: 'residential',
    status: 'sold',
    approvals: ['NMRDA Sanctioned', 'RL Approved'],
    loanEligible: false,
    description: 'A completed and fully occupied plotted development situated directly on the Wardha Road growth corridor. All plots have been sold.',
    features: [
      'Wardha Road Corridor',
      'NMRDA & RL Sanctioned',
      'Clear Legal Title',
      'Delivered & Handed Over',
    ],
    image: '/PROPERTY/Kuhaasa.png',
    coordinates: { lat: 21.045, lng: 79.062 },
    featured: false,
  },
];
